### ISSUE TITLE
ValueError

### ISSUE THREAD

**Issue by jaimebayes** [rizkysifaul/PyCon2019#1]
Hi, 

I am getting this error: ValueError: Mixing dicts with non-Series may lead to ambiguous ordering.
after run this line: data_kec = pd.read_json('./data/Kecamatan_Surabaya.geojson')
Any suggestion? Thanks in advance, 

JL

**Comment by rizkysifaul** [comment]
Thank you so much for asking, actually after checking for myself I realized that the code is not working, so instead of just using this line `data_kec = pd.read_json('./data/Kecamatan_Surabaya.geojson')`, I decided to change using `data_kec = json.load(open('Kecamatan_Surabaya.geojson'))`. Also, I have updated some few codes on file Gather All of Your Data.ipynb for you to check it out. Thanks a lot.

**Comment by jaimebayes** [comment]
OK, i will try again to check how it works now.
Thank you very much, 
Have a good day
